### ISSUE TITLE
inline comment docs

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#100]
Over in mapbox/mapbox-ios-sdk#4 we've been working on [appledoc](http://gentlebytes.com/appledoc/)-based documentation. I was wondering what your thoughts on this were, since putting it into ours will likely involve some rearrangement of header files in order to make more conceptual sense. This would introduce merging difficulty, as well as just introducing header comment chattiness in order to meet the needs of appledoc. I'm wondering if you'd be interesting in absorbing these changes as well in your version.

**Comment by trasch** [comment]
Actually, I removed most of the old doxygen comments to do exactly that, but I never really had the time to do it... I would be happy to merge these changes back!

**Comment by incanus** [comment]
Cool, I will open a pull request when the time comes, then. Thanks!
