### ISSUE TITLE
improvements from MapBox

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#104]
So we've just done a release over on the [MapBox iOS SDK](https://github.com/mapbox/mapbox-ios-sdk) and I've got a number of improvements to send up to you. At the very least, it's many pull requests, so I wanted to run them by you upfront and get a sense of whether you want some or all. I will try to combine the ones you want logically by feature area so they are a bit easier to review. 
### Features I'm guessing you'll want
- Documentation improvements per #100. You can get a sense of the scale in 93f7a3c013c7991d96093befbb0e4d6242bbd347 This will probably the last one you want to integrate, after the other changes. 
- A new map view background like MapKit's. If not otherwise presented with a `backgroundImage`, a map view gets an `RMTileLoadingView` (internal variable like the scroll view) that has a grid background image. The difference is that it moves with the map panning, so it provides some context for before tile images load. When zooming, the grid lines disappear, just like MapKit, then reappear when zooming is complete, and the effect is pretty nice overall. 
- User location annotation can be tapped & notifies delegate like in MapKit. 
- Heading calibration UI exposed as a `BOOL` and added option to auto-remove it after ten seconds if still visible more like MapKit. 
- Added `BOOL` arguments to the before/after map pan/zoom delegate callbacks to let the delegate know if this was related to a user action (touch) or not (centering on user location, programmatic zoom, etc.) See [this method](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapViewDelegate.h#L72) for example. 
### Bug fixes & tweaks I'm guessing you'll want
- Fixed a bug where annotations could falsely report being visible. 
- `RMMapViewDelegate` now exposed as an `IBOutlet`. 
- Made delegate before/after pan/zoom actions only fire once, and every "before" is guaranteed to get a matching "after". 
- All marker annotations now get ordered in the z-index from the top of the map to the bottom, including adjusting on the fly during heading rotation, so that they overlap properly like MapKit. In addition, clusters get placed below all non-cluster annotations (can change with a `BOOL`) and user location annotations are below everything else. 
- Some fixes to heading tracking/rotation in response to device orientation rotation. 
- Fixes to annotation rotation during heading tracking for annotations that start off screen and then come on. 
- Fixes to map de-rotation when turning off heading tracking (syncing up annotation counter-de-rotation duration). 
- Fixes to user tracking centering based on previous zoom level. Map doesn't zoom in to local view unless at a very low zoom level, but rather just re-centers. 
- Better error handling when user location services are denied or disabled. 
### Features that I'm not sure if you will want or not
- Improved tile load performance per my latest comments in #35, including defaulting `missingTilesDepth = 1`. You can see the diff at a90ff6c7f9c4dcd042d02562502a90cb7c230e92
### Bug fixes & tweakies that I'm not sure if you will want or not
- Map pan deceleration now defaults to `RMMapDecelerationFast` like MapKit. 
- `RMMapView` protocol adoptions moved into private API so they don't show up in the new docs. 
- Added assertion to ensure graphical assets for user location and loading tile background are bundled with the app.

**Comment by trasch** [comment]
I really like  what you're doing here, thanks for all your efforts!

I'd like to apply all of them to this fork. I'm not sure if not some of them break our apps but I'll find that out. #35 might actually break something I'm currently working on, but that's also easy to fix and if you're happy with it I am sure I will be happy with it as well... :)

Again, thanks for all the work you're putting into this and for sharing all the patches!

(Especially, I like the patches that end with "like MapKit"... :)

**Comment by incanus** [comment]
Ok. I'll still try to break it up a bit so it's easier to go through, if it doesn't drive me crazy ;-)
