### ISSUE TITLE
RMMapView in UISplitViewController app, causes duplicate tile handling 

### ISSUE THREAD

**Issue by tagcat** [Outdooractive/route-me#115]
When RMMapView is placed in the detailedviewcontroller of a UISplitViewController, RMMapTiledLayerView.drawLayer get called twice for the same rect each in their own thread. Thus all map tiles get double retrieved and caches. Can demonstrate by taking code from mainviewcontroller from markermurder sample code, and implementing in the detailviewcontroller.

**Comment by incanus** [comment]
I believe this is a known bug in CATiledLayer and has been filed with Apple.

**Comment by tagcat** [comment]
Is this unique to UISplitViewController, or anytime we have two subview in one windows? I see the same symptoms with the clone MGSplitViewController. If so is there any workaround.
