### ISSUE TITLE
Zoom with zoomWithLatitudeLongitudeBoundsSouthWest creating half-size tiles on iPad2

### ISSUE THREAD

**Issue by tagcat** [Outdooractive/route-me#119]
When using zoomWithLatitudeLongitudeBoundsSouthWest to set an initial zoom level resulting in a non-even zoom level, the next normal zoom level is downloaded from the web, but scaled to half size, thus 4x as many tiles as required.  All other zoom or pan changes that follow in the scroll view, keeps using the smaller tiles, thus all actions keep downloading 4x data required, even when for a normal-even zoom level.  Not only are we downloading much more data then required but scale down of tile makes content fuzzy.  An issue with non-retina ipad (Does not appear to be an issue on Retina).  iOs 5.2 not tested with 6.0

Example:
Can demonstrate with markermurder 

```
CLLocationCoordinate2D ne = {.latitude = 53.152,.longitude=7.138};
CLLocationCoordinate2D sw = {.latitude = 51.209,.longitude=3.469};
[mapView zoomWithLatitudeLongitudeBoundsSouthWest:sw northEast:ne animated:YES];

[self updateInfo];
[self performSelector:@selector(addMarkers) withObject:nil afterDelay:0.5];
```

(remove existing center and zoom statements)

**Comment by tagcat** [comment]
Having experimented with settings etc and having read many-many comments concerning this behaviour with catilelayer, I think we have to except that what you get out of this black-box.

**Comment by incanus** [comment]
Yes @tagcat, that's right. Unfortunately yes, physical size of the tiles can frequently be below the 256px tile image size due to fractional zoom levels being possible on iOS (versus, say, a web mapping client). We are working on ways to optimize performance here.

**Comment by tagcat** [comment]
For me the issue is not primarily ( but never the less import) the number of tiles required to paint the screen, but the non-intuitive behavior. Zoom from 10 to 10.000001 and the screen content gets much much smaller.   On a non-retina screen a rather fussy tile is the result. The regular route-me handles that much better. But it has the advantage of being in control.
