### ISSUE TITLE
Markers wiggle in higher zoom levels

### ISSUE THREAD

**Issue by tkohout** [Outdooractive/route-me#128]
Reconstruction:
1. Open Marker murder sample application
2. Zoom in as much as you can to one of the markers (Zoom level 18)
3. Move with map, you will see marker wiggling

It's worse with higher zoom levels. I have found possible problem, more in this thread:

http://stackoverflow.com/questions/14678926/route-me-alpstein-fork-for-ios-markers-wiggle-in-higher-zoom-levels

**Comment by incanus** [comment]
This is being tracked here as well: https://github.com/mapbox/mapbox-ios-sdk/issues/72
