### ISSUE TITLE
MapBox 1.0.0 changes

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#129]
Hi @trasch, I'm going to be issuing a pull for the latest MapBox stuff from our 1.0.0 release last month -- changelog [here](http://mapbox.com/mapbox-ios-sdk/changelog/). 

The only really invasive change is ARC support, so I wanted to open a ticket with you to discuss before I send that up, as well as to see where you are in a possible dev cycle of your own so we can best merge (if you want to).

**Comment by trasch** [comment]
Hi @incanus, that would be great! I'm not doing much for route-me at the moment since I'm currently busy with other stuff, so there shouldn't be many conflicts.

**Comment by incanus** [comment]
Awesome, I'll queue that up.
