### ISSUE TITLE
adding markers to mbtiles demo

### ISSUE THREAD

**Issue by krisbulman** [Outdooractive/route-me#13]
Can markers be added to the mbtiles demo? If so, tips? 

the moment I change to a local tile source, the markers (annotation code used from the other demos), disappear.

**Comment by trasch** [comment]
I don't see any reason why it shouldn't work. I'll check this.

**Comment by krisbulman** [comment]
Thanks, it's likely just my implementation then. 

After looking at other projects, I've noticed that there was a RMMarkerManager.m, which isn't in this release, so thought there may be something missing which was leading to my problem.

**Comment by trasch** [comment]
I just added markers to the MBTilesDemo. Please let me know if this helps you, or make a fork and check in your changes so that I can have a look at it.

**Comment by krisbulman** [comment]
Thanks, I'm actually not sure where I went wrong, but followed your code to a T and it worked like a charm.
