### ISSUE TITLE
ClusterAnnotations sample? 

### ISSUE THREAD

**Issue by krisbulman** [Outdooractive/route-me#16]
Any plans on adding an annotation clustering sample project? Or any info on how to implement would be great.

**Comment by krisbulman** [comment]
I see in the features list it actually says "Automatic annotation clustering" hmm.. My tests don't auto cluster. Maybe I am confusing the term.. This is to prevent marker overlap, right? I will post a screenshot and modified sample project shortly.

**Comment by trasch** [comment]
Updated the MarkerMurder sample with clustering
