### ISSUE TITLE
Creating annotations when touches ended

### ISSUE THREAD

**Issue by mtoon** [Outdooractive/route-me#19]
This might just be a familiarization thing, but I'd like to reload my annotations when the user lifts a finger (there is some database crunching and CG calls to generate the views) instead of when the view scrolls.  I implemented this in the old route-me by overriding touches ended, but with the new gestures and RMMapTiledLayerView paradigm, it's not that direct.  Or at least it appears to not be. 

So, before I make changes to RMMapTiledLayerView and RMMapTiledLayerViewDelegate, I wanted to see if there was any way to latch into touches ended without changing the code.

Thank you!

**Comment by trasch** [comment]
I would recommend that you try the delegate methods afterMapMove: and afterMapZoom: first, which should be similar to the behavior you want.

If you want your action only to happen after the last move or zoom, you could use something like:

```
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(updateViews) object:nil];
    [self performSelector:@selector(updateViews) withObject:nil afterDelay:0.1];
```

**Comment by mtoon** [comment]
Thank you!  That makes sense, I'll try it!

**Comment by mtoon** [comment]
This worked great, thanks!
