### ISSUE TITLE
Static RMPaths

### ISSUE THREAD

**Issue by mtoon** [Outdooractive/route-me#20]
Sorry about all of the posts, please let me know if there's a better "forum"-esque place to ask these questions..   Is there anyway to add a static path to the map?  In the old route-me, I could do something like this to create a box RMPath:  (See remark at bottom).  Thank you!

```
if (self.nearbyItemsPath) {
if (self.nearbyItemsPath.superlayer) {
    [self.nearbyItemsPath removeFromSuperlayer];
}
    self.nearbyItemsPath = nil;
}

self.nearbyItemsPath = [[[RMPath alloc] initWithContents:self.mapView.contents] autorelease];
self.nearbyItemsPath.lineColor = [UIColor whiteColor];
self.nearbyItemsPath.fillColor = [UIColor lightGrayColor];
self.nearbyItemsPath.opacity = 0.80;
self.nearbyItemsPath.lineWidth = 3;

[self.nearbyItemsPath moveToLatLong:CLLocationCoordinate2DMake(ne_lat, ne_lon)];
[self.nearbyItemsPath addLineToLatLong:CLLocationCoordinate2DMake(sw_lat, ne_lon)];
[self.nearbyItemsPath addLineToLatLong:CLLocationCoordinate2DMake(sw_lat, sw_lon)];
[self.nearbyItemsPath addLineToLatLong:CLLocationCoordinate2DMake(ne_lat, sw_lon)];
[self.nearbyItemsPath addLineToLatLong:CLLocationCoordinate2DMake(ne_lat, ne_lon)];
self.nearbyItemsPath.zPosition = C_ZPOSITION_NEARBY_ITEMS;
```

// THIS IS THE KEY thing that doesn't work anymore (obviously because contents no longer exists, but is there an alternative way to do this?  I have experimented with paths as annotation markers, but that is a very cumbersom way to simply add a quick static path.  
    [[self.mapView.contents overlay] addSublayer:self.nearbyItemsPath];

**Comment by mtoon** [comment]
BTW.. If it's not currently possible, please let me know how you might implement it and I can flesh that out and upload it.
Thanks!

**Comment by trasch** [comment]
It's not designed to handle layers on the map without an annotation, since there is a lot of logic attached to the annotations, like moving the annotation layers with the map (map and layers are two different views).

If you really want to try it, have a look at

```
- (void)correctPositionOfAllAnnotationsIncludingInvisibles:(BOOL)correctAllAnnotations wasZoom:(BOOL)wasZoom;
```

especially

```
[overlayView addSublayer:annotation.layer];
```

But I doubt you will be happy with static paths...

**Comment by mtoon** [comment]
I'll take a look...  Is there any interest in supporting "static layers"?  If so, I can start working on an implementation of that, otherwise I might try and keep to the annotation route to stay compatible with the library going forward (I really like this new iteration of the route-me library, I am just having a couple of legacy conversion issues, but getting my custom tile sources up to speed was no problem and I love the more efficient memory footprint, so thanks to everyone that have already contributed!).

**Comment by trasch** [comment]
Is this related to #18? If so, it would probably be better to solve that problem first. Adding layers to the map without annotations is not really intended usage, so it might be easier to look for other solutions first... :)

**Comment by mtoon** [comment]
Yes, it's related.  I think the bounding box idea might be perfect.  I basically need the ability to place some RMMapLayers on the map for various elements that are not specific points, rather "regions"..  So, RMCircle, custom RMPaths and other items that descend from RMMapLayer.  However, I think whatever comes out of #18 is going to solve this one as well.
