### ISSUE TITLE
Map tiles disappear after loading finishes

### ISSUE THREAD

**Issue by cellininicholas** [Outdooractive/route-me#22]
Sometime map tiles disappear soon after they have finished loading.

Is this because a tile with a different zoom level starts to load on top of the old tile?

**Comment by trasch** [comment]
Map tiles should not vanish, they are replaced by new tiles if you change the zoom level.

It is difficult to comment on this. Is this happening with the included samples, or with your own app (and tile source?)

**Comment by trasch** [comment]
Is this still happening with the latest commits? Do you maybe have a sample project?
