### ISSUE TITLE
setConstraintsSouthWest: NorthEast:

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#28]
I have trouble setting constraints to prevent the user from scrolling outside a specific area. I use the following code, where all variables are set to reasonable values.
# define Latitude 47.56
# define Longitude 10.22

```
self.mapView = [[RMMapView alloc] initWithFrame: fullscreen
                                  andTilesource: tileSource
                               centerCoordinate: CLLocationCoordinate2DMake(Latitude, Longitude)
                                      zoomLevel: InitialZoom
                                   maxZoomLevel: MaxZoom
                                   minZoomLevel: MinZoom
                                backgroundImage: nil];

[self.mapView setConstraintsSouthWest: CLLocationCoordinate2DMake(Latitude-0.1, Longitude-0.1)
                           northEeast: CLLocationCoordinate2DMake(Latitude+0.1, Longitude+0.1)];
```

With this code I am not able to move the map at all. Am I doing something utterly wrong?

If I use the original route-me implementation and invoke setConstraintSW: NE: with the same arguments the map is constraint as I would expect.

**Comment by trasch** [comment]
It should work, at least I have some projects that use it. Have you tried a bigger constraint?

**Comment by jan-christiansen** [comment]
I tried an offset of `100` instead of `0.1` as well as static values that span an area of more than one hundred kilometers. I even used `initWithFrame:` and latitude and longitude of `centerCoordinate` to rule out wrong zoom level settings, still no luck. Is there anything else I might have forgotten?

**Comment by trasch** [comment]
This is indeed a bug. I'll have a look at it.
