### ISSUE TITLE
Assertion failure after uncovering RMMapView

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#34]
I have an application that presents a map view. First, I zoom in as far as possible. Then, I tap on a mark, which causes a new view controller to cover the map. I wait some seconds and dismiss the view controller again. After dismissing the view that covered the map, the map shows no tiles, that is, it is completely grey. But, more importantly, I get an assertion failure. More precisely, the method `URLForTile` in `RMMapQuestOSMSource` raises an exception because the current zoomLevel is 19 while it may only be 18 for the MapQuest source.

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<RMMapQuestOSMSource: 0x184780> tried to retrieve tile with zoomLevel 19, outside source's defined range 1.000000 to 18.000000'
```

Can somebody explain me what is happing when the map view is covered?

**Comment by jan-christiansen** [comment]
Now that I have read the other issues _cough_ this issue looks related to issue #33.

**Comment by jan-christiansen** [comment]
This is indeed issue #33 as the failure only occurs if I chose "iPhone (Retina)" in the simulator but not if "iPhone" is chosen. In `drawRect:` of `RMMapTiledLayerView` the `width` of the `rect` is `0.00048828125` while it is `0.0009765625` when the zoom level is correctly calculated.

**Comment by jan-christiansen** [comment]
Furthermore, the error only occurs the first time the map is uncovered. That is, if the map is hidden and uncovered a second time the zoom level does not change. Additionally, even when zooming out, the minimum zoom level that is reached is 2 instead of 1. That is, the range of zoom levels is shifted by one.

**Comment by trasch** [comment]
Does the last commit fix your problem?

**Comment by jan-christiansen** [comment]
Works fine now, thanks a lot.

**Comment by jan-christiansen** [comment]
By the way this commit even fixes a problem with setting `adjustTilesForRetinaDisplay`. The result of setting this property and other properties depended on the order, while this now doesn't seem to be the case any longer.
