### ISSUE TITLE
clearsContextBeforeDrawing

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#37]
I have to admit that I have no experience at all in this area but when I just read the following paragraph about drawing in a view

> Another way to improve drawing performance, especially during scrolling, is to set the clearsContextBeforeDrawing property of your view to NO. When this property is set to YES, UIKIt automatically fills the area to be updated by your drawRect: method with transparent black before calling your method. Setting this property to NO eliminates the overhead for that fill operation but puts the burden on your application to fill the update rectangle passed to your drawRect: method with content.

I wondered whether it is possible to set `clearsContextBeforeDrawing` of `RMMapTiledLayerView` to `NO`. As the `opaque` property of `RMMapTiledLayerView` is set to `NO`, I suspect that there are settings that use transparent tiles. Is this right? Does anybody have experience with the performance for different settings of `clearsContextBeforeDrawing` and `opaque`?

**Comment by trasch** [comment]
Have you tried this?

I can't see any difference, and the main bottleneck for the map view is still image decoding (decoding images into memory is really slow...)

**Comment by jan-christiansen** [comment]
No, I did not try it.
