### ISSUE TITLE
Truncated, hopping RMCircle with tap zooming

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#38]
When zooming in using taps, it looks like the position of `RMCircle`s on the map is altered. The circle sometimes even looks truncated by some kind of rectangle, possibly the `CGRect` passed to `drawRect:`. This issue may very likely be related to issue #29.

**Comment by trasch** [comment]
I think I fixed this with commit ccdc7282692b34f47e0c9f859f896638c0ee0a10.
