### ISSUE TITLE
Slow on the iPad 3?

### ISSUE THREAD

**Issue by mtoon** [Outdooractive/route-me#39]
Just curious if anyone else is seeing this..  The map seems to redraw slower on the iPad 3...  It actually looks like the tiles are still being drawn at 256x256, but the higher resolution is basically making lots of smaller chunks.  I might be totally off here, but it does look like it's drawing 4x as many chunks.  I'm sure for people with great tiles this makes the maps look awesome especially when zoomed out, but for us, the map doesn't have a lot of detail and the higher resolution is really "taking too much time" according to the users!

Thoughts?

Thanks!

**Comment by trasch** [comment]
Try the adjustTilesForRetinaDisplay property... :-)

**Comment by mtoon** [comment]
Whoa.  Much better!  Thank you!

**Comment by mtoon** [comment]
Quick question..  Do I need to check for the device capabilities and set this differently for iPad1,2 and iPhone < 4?

Thank you!

**Comment by trasch** [comment]
No, this will be handled for you.

Have a look at createMapView in the RMMapView class, there is the code for retina displays.

**Comment by mtoon** [comment]
Perfect, thank you!
