### ISSUE TITLE
Apple rejecting all apps linking against libMapView.a because of UDID usage

### ISSUE THREAD

**Issue by krisbulman** [Outdooractive/route-me#40]
Just wanted to be sure this discussion has also been seen by the users of this fork

https://groups.google.com/forum/#!msg/route-me-map/K8meASFFa0U/zv0HmnN7LNEJ

(oringally posted in response to this article http://arstechnica.com/apple/news/2012/03/after-warning-from-apple-apps-using-udids-now-being-rejected.ars )

**Comment by trasch** [comment]
Ok, I'll track this issue, but since the cloud made tile source hasn't been ported to this fork yet, I'll close it for now.
