### ISSUE TITLE
MapBox/TileStream changes (pull request not working)

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#42]
I tried to do this over in #41, but GitHub is being odd in that it's trying to relate your fork and Route-Me core instead of just the one commit that I wanted to send to you. 

Anyway, the commit is 287f307887ef190bd0957a3c7846de942af7d379 and is described in Route-Me core [here](https://github.com/route-me/route-me/pull/172). I've replicated the changes for your fork as well, since that's what I'm using these days. 

Let me know if you'll consider it for your fork.

**Comment by trasch** [comment]
Sure, but it will take some time to manually apply the changes, unless you could create a pull request in the context of the Alpstein fork.

**Comment by incanus** [comment]
Sorry @trasch. I think you can get it with `git cherry-pick 287f307887ef190bd0957a3c7846de942af7d379` after `git remote add mapbox git://github.com/mapbox/alpstein-route-me.git` & `git pull`, but I will try again to create a proper pull request. I think GitHub was misbehaving last week.

**Comment by incanus** [comment]
Nope, no luck. The pull request preview shows "1 commit, 4 files changed" but switching to those tabs indicates hundreds of commits from upstream Route-Me. I'm just not sure why.
