### ISSUE TITLE
boundingMask not limiting pinch-zooming

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#43]
Is it intended behavior that the boundingMask limits only two-finger tap zooming out, but not pinch gestures? I can zoom out far enough that the view background is visible. 

Just curious if this is known -- I'll take a look at it but wanted any background info first.

**Comment by trasch** [comment]
No, this is not intentional... There are more bugs with constraints, see also #30.

**Comment by incanus** [comment]
I believe I've solved this with 351f1bbb12ade9b9bed55da2790d72f7ab6e84a5, but unfortunately GitHub is again not letting me do a pull request.

**Comment by incanus** [comment]
Somewhat related: how do you feel about a `BOOL` flag for this setting, and, if `YES`, a way to have the map view automatically limit to the shortest of the height/width dimensions? Basically, whether to limit or not, and not worry about height or width or which is bigger/smaller.

**Comment by incanus** [comment]
Another commit here, for when the frame is changed: f47dd74f646ed4df3d92e2500ef7f68bca70be40

Sorry about the difficulty here -- I have a support issue open with GitHub about this. I think it might be related to me forking your fork and trying to send pull requests back, though I swear I did this ok before.

**Comment by trasch** [comment]
I think a `BOOL` would be totally sufficient for this, but I don't really have an opinion on this since I never used this particular feature (at least not knowingly)...

**Comment by incanus** [comment]
With MapKit, you never can zoom out beyond the whole-world zoom level. Granted, with Route-Me we can clamp to greater zoom levels, but I still think you shouldn't ever see background unless desired (`BOOL` set to `NO` in the above example). So I'll look into adding this behavior. 

Thanks for taking the patches, and sorry about the continued pull request problems...

**Comment by incanus** [comment]
Ok, I will track that `BOOL` enhancement myself and try to get to it. Otherwise I think if my code above works, we're done here.
