### ISSUE TITLE
Implementing RMPath using CAShapeLayer

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#44]
Because I had performance problems with using complex paths, I implemented a version of RMPath that uses a CAShapeLayer. First tests with a device indicate that it improves performance significantly, at least in my application. I have posted a prototype, which probably has lots of bugs, in the following gist.

https://gist.github.com/2350064

Any kind of comment is very welcome. Are there any known issues that prevent using a CAShapeLayer?

**Comment by trasch** [comment]
Thanks for the patch, I added a branch for it (`path_shapelayer`) and will test it

**Comment by trasch** [comment]
Added your RMShape to the project, see #29. Thanks for this, its really a major improvement.

**Comment by jan-christiansen** [comment]
When I played with the implementation of paths by means of a shape layer the performance improved when setting `shouldRasterize` when the path is scrolled. I have opened a pull request (issue #75) that sets the property accordingly.

**Comment by trasch** [comment]
I removed this on purpose since it introduces some other problems, i.e. in high zoom levels the path will vanish if you just move the map until you lift your finger again.

This happens when using `[self.layer scrollPoint:CGPointMake(-delta.x, -delta.y)]` but I haven't found out why exactly this rather unexpected behaviour happens.

Maybe it would be feasible to only set `shouldRasterize` on lower zoom levels, I'll check that out...

**Comment by jan-christiansen** [comment]
Ah, I was not aware that you took this into account. Sorry, that I did miss out on the odd behavior for higher zoom levels. I would rather advocate for leaving it out completely as there might be other unexpected behaviors. When I read about `shouldRasterize` there where several comments that reported surprising behavior.

**Comment by trasch** [comment]
Ok, I think its better to be on the save side here. Thanks for your efforts!

**Comment by incanus** [comment]
Loss of shadow here when compared to `RMPath`. Will try to adapt & send pull request.

**Comment by KrauseFx** [comment]
Does this change also completely fix the jittering bug: https://github.com/Alpstein/route-me/issues/29 ?
Where is the latest version of this improvement/fix?

**Comment by trasch** [comment]
Yes, and it's in the develop as well as the release branch.

**Comment by KrauseFx** [comment]
Maybe I'm doing something wrong, but I've updated the route-me files (release branch) and use the following code for rendering the route now:

```
RMAnnotation *routeAnnotation = [[RMAnnotation alloc] initWithMapView:self.mapView
                                                                   coordinate:((TSPoint *)[[self.currentRoute points] firstObject]).location
                                                                     andTitle:@""];
        routeAnnotation.annotationType = conAnnotationRoute;
        [self.mapView addAnnotation:routeAnnotation];
```

and in the `- (RMMapLayer *)mapView:(RMMapView *)aMapView layerForAnnotation:(RMAnnotation *)annotation` method I use the following:

```
// That's a route
        RMPath *path = [[RMPath alloc] initWithView:self.mapView];
        for (TSPoint *point in [self.currentRoute points])
        {
            [path addLineToCoordinate:point.location];
        }
        [path setLineWidth:3.0];
        [path setFillColor:[UIColor redColor]];
        [path setDrawingMode:kCGPathStroke];
        return path;
```

And I have still the problem: the displayed route jumps around when I zoom in to the map

**Comment by KrauseFx** [comment]
Okay, I've found the problem: I have to use RMShape instead

```
RMShape *path = [[RMShape alloc] initWithView:self.mapView];
        for (TSPoint *point in [self.currentRoute points])
        {
            [path addLineToCoordinate:point.location];
        }
        [path setLineWidth:3.0];

        return path;
```
