### ISSUE TITLE
Annotations set to strange positions

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#46]
When I tried to use explicit animations instead of implicit once to improve path drawing, I have observed a strange behavior of `RMAnnotation`. It looks like my annotations are set to positions far out of bounds before they are set to their designated position. For example, when zooming in by double tap, my annotation is set to position

  (138693.671875, 86909.796875)

before it is set to position

  (100.679443, 175.798996)

I think these position changes result in artifacts when using animations. Are these strange positions intended?

**Comment by trasch** [comment]
I copyied this to #29 since it's really the same issue IMO so that we don't have duplicates. If we manage to fix this we will also fix some other problems...
