### ISSUE TITLE
Multiple tile sources at once

### ISSUE THREAD

**Issue by hryamzik** [Outdooractive/route-me#47]
Hello,

I've made some modifications to this fork of route-me to work with multiple tile sources at once. So map view operates with a special TileSources object that responds to some methods of RMTileSource protocol and contains mutable array of tiles sources. Instead of a view for tile source that's originally placed inside of a UIScrollView I've added a simple container UIView and add/insert multiple tile source views to it. That seems to be a better way for displaying layers than adding multiple map views and syncing touch events between them (that's what google suggests for layers). 

I've also done some modifications to cache code to be able to delete it for specified tiles. 

I've made some work on RMGenericMercatorWMSSource, it could be found on web in multiple versions. I've chosen one and implemented a no-caching option, it was done in ARC enabled project thought.

My "fork" is not a complete solution, at least I didn't implement all the methods of RMTileSource for tile source "container", but I think it could be useful and ones who'll miss some methods could easily implement them. 

I don't like the idea of creating a new fork, what about adding it to this project, probably in some separated way (in a brunch)?

**Comment by trasch** [comment]
You could either push your changes to your GitHub account were I could have a look at it and pull it into a branch, or you could send me a patch (you could use a Gist for this).

Thanks for your efforts!

**Comment by hryamzik** [comment]
Thomas, did you get my mail?

**Comment by trasch** [comment]
Yes, I got it. Sorry for my silence, but I am currently busy with an important project, I'll have more time next week.

**Comment by trasch** [comment]
Ok, I just checked the patch and I think it would be much better suited for a fork.

Just add it to your GitHub account and change the Readme to describe your changes.

**Comment by incanus** [comment]
I will check out your approach too, @hryamzik, as I think I would like the tiles to not reload when enabling/disabling layers. Let me know if you do end up forking this.

**Comment by vakulenkom** [comment]
Hello guys!
I am new to git, but really need to implement route-me map in my project. So i need little help from you.
I downloaded hryamzik's path from https://groups.google.com/forum/?fromgroups#!topic/route-me-map/JQIUN-dYY_w
and applied it to Alpstein route-me fork by using console command "git apply mts.patch". But unfortunately i got a lot of errors. 
What i am doing wrong?

Thanks in advance!

**Comment by vakulenkom** [comment]
@hryamzik 
What i need is just branch and commit, where i should apply ur patch. Please, help me!

**Comment by incanus** [comment]
Wanted to ping on conversation about this… in looking into it, this approach of multiple stacked views seems like it will work better for us ([MapBox iOS SDK](https://github.com/mapbox/mapbox-ios-sdk)) as well for three main reasons: 
1. Map won't have to fully reload upon reordering or toggling of individual layers. 
2. Caching is better handled at the tileset level. 
3. Introduction of [retina tiles](http://mapbox.com/blog/retina-tiles-available-ios-sdk/) means some layers will benefit from 512px tiles (`adjustTilesForRetinaDisplay`) and some from staying at 256px, but this is hard to do in a single composited layer. 

I've put together a quick performance test at https://github.com/incanus/TileTest showing multiple views contained in a superview which is the scroll view content view. This works well and is fast. 

Any thoughts @trasch?

**Comment by hryamzik** [comment]
I'll do my best to publish code in a fork this week. It'll take some time to move my functions to current version.

**Comment by trasch** [comment]
@incanus I agree, and I think we should get rid of the current tile compositioning in the tile source as soon as we get this to work. Or am I missing some use case where the current implementation would be better than stacked views?

**Comment by hryamzik** [comment]
Finally published.
https://github.com/hryamzik/route-me
I've simply cloned latest version and pasted my project on top of it. My project is based on a 2 months old clone though. I'll try to find some time to move my functions to current release.

**Comment by incanus** [comment]
@hryamzik, thanks for this, and thanks @trasch for reopening. I'll give the fork a try. I can likely help out since I have an active need for this right now, too.

**Comment by hryamzik** [comment]
Feel free to contact me if you'll have any questions. I didn't find time to document modifications yet. Some usage is listed on main page, there are some other things though, such as ability to remove individual tile cash.

**Comment by incanus** [comment]
One downside to this approach as committed above is any chance to the tile sources causes a refresh of the full view by nulling out all the tile layers' contents. Avoiding this was one of the big reasons to move to multiple tile layers in the scroll view instead of image compositing.

**Comment by hryamzik** [comment]
There's another reason: if you have a dynamic layer, you can still use caches for static ones.

**Comment by trasch** [comment]
@incanus Recreating the map view is the safest option here, but I wil see if I can improve it. That's why I added the hideTileSource/showTileSource methods, the intention is to add all tile sources at once and then hide or show the individual layers.

@hryamzik What exactly do you mean? The cache works on individual tile sources, so there shouldn't be a problem in this regard.

**Comment by incanus** [comment]
I will see if I can help, too. My use case is an open-ended layer browser, where you don't know what sources might be brought into the app, allowing free rearrangement and toggling.

**Comment by trasch** [comment]
I think this issue should be done now, but I don't have that many use cases for multiple tile sources to test it extensively. Can anyone comment on this?

**Comment by incanus** [comment]
I will check this out this week, hopefully on the sooner side.
