### ISSUE TITLE
MarkerManager moveMarker?

### ISSUE THREAD

**Issue by hryamzik** [Outdooractive/route-me#49]
This project doesn't contain MarkerManager class, so I wonder if there's a smooth way to move markers/annotations.

**Comment by trasch** [comment]
Do you want to enable dragging on the markers?
-> Have a look at RMMapLayer.h and RMMapViewDelegate.h. (i.e. set enableDragging=YES on the layer and implement the delegate methods for marger dragging)

Or do you want to programatically move the markers?
-> Set a new coordinate to the appropriate annotation.

**Comment by hryamzik** [comment]
My bad, already done this by changing annotation coordinates. Thought it should be animated. =)
