### ISSUE TITLE
Zoom to next native zoom uses odd factor

### ISSUE THREAD

**Issue by jan-christiansen** [Outdooractive/route-me#50]
For example, I get the following output.

```
zoom in from:10.000000 to:10.990000 by factor:1.986185 around {136.000000,247.500000}
```

Furthermore, it looks as if `nextNativeZoomFactor` and `previousNativeZoomFactor` are not used.

**Comment by trasch** [comment]
This is intentional because it prevents some annoying effects during zooming. This is also the reason why I haven't used `nextNativeZoomFactor` and `previousNativeZoomFactor` since there is some extra calculation involved.
