### ISSUE TITLE
rotating map view? 

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#52]
@trasch, have you any experience with rotating either the whole map view or the tiled layer? I have been working on a an app over at https://github.com/mapbox/mapbox-me that behaves like Maps.app and has a tracking dot, halo, and compass directional, as well as a rotating map view, but I've faked it by making the map view bigger than specified in order to not show background when being rotated at a diagonal. 

Looks like this: 

![](http://dl.dropbox.com/u/575564/mapbox-me.png)

Any ideas for a better approach? I'd like to contribute the code back to the project directly so that it behaves more like iOS 5's MapKit -- right now it's just contained in this app's logic.

**Comment by trasch** [comment]
That's exactly how I do it, although I have a few more requirements. CATiledLayer is actually quite smart in that it really only loads the visible tiles, so enlarging the map view is not much of a problem (in my experience, at least).

**Comment by incanus** [comment]
Ok, just curious. The one problem I've seen with this approach is if the map stays rotated, getting to the bounds or constraints does weird things, since they are technically out of view because of the rotation corner-covering. But for Maps.app-like behavior where if you pan, the map rotates back to normal orientation, it works fine (providing you aren't physical located near the meridian or the poles).

**Comment by trasch** [comment]
My solution was to always rotate back to the normal orientation as soon as the user interacts with the map, like Maps.app. If you don't want to do this, then you'll have to take the rotation into account for every constraint or bound which might not be worth the work...

**Comment by incanus** [comment]
Yeah, that's what I'm doing. I've added a pinch & zoom simultaneous gesture which only serves to un-rotate the map if the center point gets moved.

**Comment by incanus** [comment]
FYI, the way I've tackled this over in #59 location services was to set `clipsToBounds = YES` for `RMMapView` itself but `NO` for the contained `UIScrollView`, then rotate the scroll view inside of the map view. That way, overlays get rotated as well.
