### ISSUE TITLE
adjustTilesForRetinaDisplay for retina displays

### ISSUE THREAD

**Issue by fredleefarr** [Outdooractive/route-me#54]
Hi, I'm trying to make the map appear sharper on the iPhone 4 by setting the following:

mapView.adjustTilesForRetinaDisplay = YES;

However, I can't see any difference in the map on the device, whether I set YES or NO.  

I'm setting the value in SimpleSampleMap, in viewDidLoad, before [self.view addSubview:mapView].

I've also tried setting adjustTilesForRetinaDisplay = YES in RMMapView's performInitializationWithTilesource, and setting the screenScale to 2.0 there. 

is there anything else I can try?

Thanks.

**Comment by fredleefarr** [comment]
I've tried digging into the code, and can see that the map renders in a different way when adjustTilesForRetinaDisplay is set to YES - specifically in RMMapTileLayerView.drawLayer() - but the map still appears the same. Strange.

As a work-around I can provide tiles sized at 512px instead of the standard 256px (I have my own tile server). This creates a crisp, sharp map - but the larger tile size isn't ideal.

**Comment by incanus** [comment]
Hmm, the effect I see with this with normal 256px tiles is to draw them at 512px, which looks not as good, but accounts for readability issues with drawing 256px at a literal 256px on retina devices, where the text and features are too small.

**Comment by trasch** [comment]
Fixed with the latest commit 7a452e70b2e2e94c7cdb0280deac5453c6e24bcb

**Comment by fredleefarr** [comment]
Thanks @trasch - I can see the difference now.
