### ISSUE TITLE
rearranging stacking order of map layers

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#55]
Have you experimented at all with allowing methods on `RMMapView` for rearrangement of annotation layers within the private `RMMapOverlayView`? I need this functionality and am going to start on it, but was wondering if you had ever ventured here. 

Will contribute when I get it working. I'm thinking along the lines of `MKMapView`'s `insertOverlay:aboveOverlay:` et al.

**Comment by trasch** [comment]
I haven't done anything in that direction since I never had a use case for this (clustering prevents overlapping in all of our apps). I have used the zPosition property on markers though, but that's probably not very useful for what you want to do...

**Comment by incanus** [comment]
I'm playing with `zPosition` now, yeah. Will report on how it goes. Thanks.

**Comment by incanus** [comment]
The `zPosition` seems to work nicely. It would be good to someday refactor so that the order of `annotations` reflects their actual stacking order and vice-versa, but that's for another day...
