### ISSUE TITLE
setConstraintsSouthWest:northEast & rapid pinch zoom out

### ISSUE THREAD

**Issue by fredleefarr** [Outdooractive/route-me#58]
I've noticed that performing a fast pinch-zoom gesture to zoom out sometimes causes the screen to go blank when setConstraintsSouthWest:northEast is used. I'm seeing this issue on the iPhone 4. Here is the constrains I'm using:

```
[mapView setConstraintsSouthWest:CLLocationCoordinate2DMake(51.428,-0.216))
                      northEeast:CLLocationCoordinate2DMake(51.534,-0.047)]; 
```

the initial coordinate is:
# define kDefaultInitialLatitude 51.508
# define kDefaultInitialLongitude -0.114
# define kDefaultInitialZoomLevel 13.0

Sometimes is takes a couple of zoom-out gestures in succession to see the problem.

**Comment by trasch** [comment]
I just commited a few patches that should fix this problem, at least I can't reproduce it any more. Can you confirm this?
