### ISSUE TITLE
marker label taps not working

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#6]
Do you see marker label taps work? I don't, and digging into the `hitTest:` in `RMMapOverlayView`, I don't see the label's layer ever show up, including when (manually) setting the label's `userInteractionEnabled` to `YES`.

**Comment by incanus** [comment]
Seems like it might be related to this from the [hit-testing docs](http://developer.apple.com/library/IOs/#documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/MultitouchEvents/MultitouchEvents.html#//apple_ref/doc/uid/TP40009541-CH3-SW55): 

> If you have a custom view with subviews, you need to determine whether you want to handle touches at the subview level or the superview level. If the subviews do not handle touches by implementing touchesBegan:withEvent:, touchesEnded:withEvent:, or touchesMoved:withEvent:, then these messages propagate up the responder chain to the superview. However, because multiple taps and multiple touches are associated with the subviews where they first occurred, the superview won’t receive these touches. To ensure reception of all kinds of touches, the superview should override hitTest:withEvent: to return itself rather than any of its subviews.

Perhaps because this is handled in `RMMapOverlayView` directly (due to gesture recognizers) and not in `RMMapView` (like in [regular Route-Me](https://github.com/route-me/route-me/blob/master/MapView/Map/RMMapView.m#L477-480) where it is forwarded), that's why it's not working.

**Comment by trasch** [comment]
Honestly, I have never used marker labels...

Are you already working on a fix for this? If not, I'll have a look at it, but not before january...

**Comment by incanus** [comment]
Not yet; I've looked into it and think I found the culprit, but haven't coding anything to try to forward the events yet.

**Comment by trasch** [comment]
Have you checked if it works now? I still don't use marker labels... :)

**Comment by incanus** [comment]
Yes, I did a small sample with a point marker and a label and confirmed both receive taps. I can post it if you're curious. 

## 

Justin R. Miller
http://codesorcery.net

**Comment by trasch** [comment]
No, I trust you blindly, I just wanted to be sure that I can close this issue... :)

**Comment by incanus** [comment]
Yeah, I think there are no unintended side effects (other than perhaps affecting apps that were working a certain way before due to this bug) as I checked for things like paths & circles not receiving taps.
