### ISSUE TITLE
double-tap on map zooms slower than markers

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#7]
If you double-tap the map to zoom it in, the markers all jump to their new places before the map finishes the zoom animation. 

And to be clear, I'm going to try to help with these issues -- just jotting them down :-)

**Comment by trasch** [comment]
Great!

I never found the time to track this issue down, so any patch that fixes this is welcome.

**Comment by trasch** [comment]
Still open: Synchronizing path zooming with the map
