### ISSUE TITLE
Adding 'tileDepth' property on MapView to substitute a lower zoom level tile when a higher zoom level is not available

### ISSUE THREAD

**Issue by CodeStrumpet** [Outdooractive/route-me#73]
I'm wondering if anyone can help me with the implementation of this feature.  The basic idea is that if a tilesource fails to return a tile, you try to return the relevant tile at a lower zoom level because sometimes a lower resolution tile is better than no tile at all.

This is something that was added to the original route-me project and I would love to see it ported over.  I have found this feature to be very useful when dealing with an offline tilesource that does not have a consistent maxZoom across regions.

It seems like there is a natural place to add this behavior inside of the `- (void)drawLayer:(CALayer *)layer inContext:(CGContextRef)context`  method as shown below, however I haven't been successful yet in calculating the right x & y for the tile yet.

Would anyone be able to provide advice or help in calculating the 'x' and 'y' for the lower zoom tiles and how to crop the lower zoom tile so that it lines up correctly with its neighbors?  

I think the following code illustrates the logic of successively querying the tilestore at progressively lower zoom levels after a tilesource miss, however the tile x and y are probably not being calculated correctly and there is no cropping of the resulting tile image.

```
- (void)drawLayer:(CALayer *)layer inContext:(CGContextRef)context
{
    CGRect rect   = CGContextGetClipBoundingBox(context);
    CGRect bounds = self.bounds;
    short zoom    = log2(bounds.size.width / rect.size.width);

    //NSLog(@"drawLayer: {{%f,%f},{%f,%f}}", rect.origin.x, rect.origin.y, rect.size.width, rect.size.height);

    NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];

    if (zoom == (short)ceilf(mapView.adjustedZoomForRetinaDisplay))
    {
        int x = floor(rect.origin.x / rect.size.width),
        y = floor(fabs(rect.origin.y / rect.size.height));

        //NSLog(@"Tile @ x:%d, y:%d, zoom:%d", x, y, zoom);

        UIGraphicsPushContext(context);

        UIImage *tileImage = nil;

        tileImage = [[mapView tileSource] imageForTile:RMTileMake(x, y, zoom) inCache:[mapView tileCache]];

        int tileDepth = 3;  // should be a property of MapView

        int currZoom = zoom;


        // tries to return lower zoom level tiles if tile cannot be found (not yet working)       
        while (!tileImage && currZoom >= [[mapView tileSource] minZoom] && currZoom >= zoom - tileDepth) {

            int currX = x;
            int currY = y;

            if (zoom - currZoom > 0) {
                currX = floor(rect.origin.x / (rect.size.width * (zoom - currZoom)));
                currY = floor(fabs(rect.origin.y / (rect.size.height * (zoom - currZoom))));
            }

            tileImage = [[mapView tileSource] imageForTile:RMTileMake(currX, currY, currZoom) inCache:[mapView tileCache]];
            currZoom--;            
        }


        [tileImage drawInRect:rect];

        UIGraphicsPopContext();
    }
    else // Probably due to renderInContext:
    {
    // ......
```

**Comment by trasch** [comment]
I'll have a look at it tomorrow, but first you should update your fork since it is outdated, especially the `RMMapTiledLayerView` implementation was buggy.

**Comment by trasch** [comment]
I just added this feature to the development branch. Please test it with your tile sources (I have tested it a bit, but not very extensively...).

**Comment by CodeStrumpet** [comment]
Hi trasch,

Sorry for the delay in response.  I integrated the changes and been testing with the RMDBMapSource and the missingTileDepth property set to 3.  So far the results seem great.  Thanks for incorporating this feature.
