### ISSUE TITLE
Unnamed enumeration must be a definition

### ISSUE THREAD

**Issue by dageshi** [Outdooractive/route-me#79]
Quick question, I'm using standard route-me in an app I'm building, I wanted to test Alpstein to see how it compared so I've downloaded it and tried to compile the programmaticmap sample. Unfortunately I'm getting lots of errors like 

"Unnamed enumeration must be a definition" for the typedef line of code like

typedef enum : short {

```
RMCachePurgeStrategyLRU,
RMCachePurgeStrategyFIFO,
```

} RMCachePurgeStrategy ;

I'm using xcode 4.2 on Snow Leopard with the 5.1 sdk

I've googled but can't find any mention of that particular error and nothing relating to Alpstein, have I missed something obvious?

Rob

**Comment by trasch** [comment]
Please use the newest Xcode version from the AppStore, which is 4.3.3, since enumerations with types are a pretty new feature in Xcode.
