### ISSUE TITLE
non-standard C extension

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#80]
Per a [support issue](http://support.mapbox.com/discussions/mapbox-ios-sdk/101-adding-the-mapbox-ios-sdk-to-an-xcode-4-project) we're seeing, commit d68b0576 introduced some non-standard Microsoft C extensions when declaring `typedef enum`'s. Any thoughts, @trasch?

**Comment by trasch** [comment]
Well, Apple introduced this with Xcode 4.3 (and LLVM 3.1, which includes support for C++11, which - I think - introduced this feature), so it's not actually non-standard... See WWDC videos 405 and 411 for a discussion on this topic.
I wonder why your customers are using older versions of Xcode?

**Comment by incanus** [comment]
Ah, that would explain why I hadn't seen the problem, and I missed that at WWDC. They did say something about compiler flags, but I'll close here and investigate further myself. Thanks.

**Comment by incanus** [comment]
Ah, it actually seems to be introduced in the version which may or may not have gone GM just yesterday, not 4.3. So maybe this should wait until later in the month? See also https://github.com/Alpstein/route-me/blob/release/MapView/MapView.xcodeproj/project.pbxproj#L581

**Comment by trasch** [comment]
Hm, we have been building our projects with Xcode 4.3.3 for a while now without a problem, and they all include the release branch of route-me. But I will check that anyway, to be sure.

**Comment by trasch** [comment]
LLVM 3.1 was also included in Xcode 4.3.2 which has been release a while ago...

**Comment by incanus** [comment]
Thanks for the back and forth here. Turns out they were using older Xcode and LLVM GCC. We can close this.
