### ISSUE TITLE
consider removing Proj? 

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#85]
In talking with @springmeyer this week, he thought that maybe since we don't handle multiple projections, we could possibly get rid of the Proj dependency and just hardcode the (unchanging) math and reduce project complexity. Any thoughts there?

**Comment by trasch** [comment]
That's ok for me, but I have read of a few people who actually use Proj4 - they could use the implementation from the original route-me though. I wonder if anyone is not using the "Google" projection (in the route-me context)?

So, short answer: yes, let's get rid of Proj4, which is an ugly mess anyway... :-)

**Comment by springmeyer** [comment]
Cool, I'm likely going to be playing around with the code for the first time in a few weeks. I'll poke at this cleanup.

**Comment by ghost** [comment]
maps.yandex.ru uses non google projection. This is leading map service for CIS region.

**Comment by incanus** [comment]
Something else to consider here, possibly as an intermediary step: just shipping a precompiled `libProj4.a` in the main distribution, since this isn't changing anyway.

**Comment by incanus** [comment]
If you like this solution, I've done it over in our fork. I've basically removed the Proj4 subproject from the Xcode project, then built both device and simulator versions and made a fat `libProj4.a` with `lipo`. In our case, it's only got `i386/armv7/armv7s` since we don't support iOS 4 and thus not `armv6`. If you'd like this as a pull, I'm happy to provide a version for you. I think this is a good approach since the Proj4 library is still on disk, it's just not (tediously) cleaned and built each time a project needs to build Route-Me. Since it's over 100 source files, this saves a ton of time.

**Comment by trasch** [comment]
Yes, I think this is a very good approach. I've been using some static librarys lately myself as well since that speeds up some things quite considerably. Im ok with '''i386/armv7/armv7s''' since the iPhone 3GS runs iOS 5, so that won't be a problem.

Thanks!

**Comment by incanus** [comment]
Ok, I'll do a pull request then and include a fat binary.
