### ISSUE TITLE
UIScrollView Bounce and Offline Data Source

### ISSUE THREAD

**Issue by GazEdge** [Outdooractive/route-me#9]
Hi All,

I have been using an offline data source. The data contains tiles from a city, and extends as far as  the city's limits. Currently, to show the whole city on the screen, the zoom level needed is 12. 

The problem I have is that when I scroll to the edge of the city, I want the UIScrollView to 'bounce'. This is not possible though because the content size of  the UIView is much bigger than the city limits.

Is there away to manipulate the scrollView to bounce within a constrained contentSize - or is this something that may need changing in the route-me code?

Any help very much appreciated.

G

**Comment by trasch** [comment]
You'll have to implement the bouncing for yourself since there is no feasible way to change the scrollview's size.

A starting point might be moveBy: for constraining the movement.
