### ISSUE TITLE
remove RMMapBoxSource & RMMBTilesSource? 

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#92]
I don't feel super-strongly about this, but would you be open to the idea of removing these sources from your version? The reason I ask is because beyond the extra things that we're doing like [RMInteractiveSource](https://github.com/mapbox/mapbox-ios-sdk/blob/develop/MapView/Map/RMInteractiveSource.h) and [MapBox-specific improvements to RMMarker](https://github.com/mapbox/mapbox-ios-sdk/blob/develop/MapView/Map/RMMarker.h#L67-72), my implementations of these two tile sources differs slightly as well. Since both are specific to MapBox, maybe it makes more sense to just maintain them in our fork? I know that I've contributed to them in the past to route-me/route-me as well, though…

Anyway, curious about your thoughts. No big deal either way. but I don't anticipate pushing changes to them up to your project unless critical...

**Comment by trasch** [comment]
Agreed, MapBox customers probably already use your fork so it's redundant here. I'll remove them.

**Comment by specialunderwear** [comment]
Right, so that totally broke my build. Where is the @incanus fork you guys where talking about?

**Comment by incanus** [comment]
You can find out more about it here: http://mapbox.com/mobile Sorry about that.
